name: Unorepo Version

on:
  push:
    branches: [main]
    paths:
      - ".changenotes/prepare.json"

permissions:
  id-token: write
  contents: write

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
      - run: git fetch --unshallow
      - run: npm install -g corepack
      - name: Setup Runtime
        uses: __RUNTIME_ACTION__
      - name: Install dependencies
        run: __INSTALL__
      - name: Build package
        run: npm run build
      - name: Version
        run: npx unorepo-alpha version --commit --tag --push --publish --release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}