name: Unorepo Version

on:
  push:
    branches: [main]
    paths:
      - ".changenotes/prepare.json"

permissions:
  id-token: write
  contents: write

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 25
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Build package
        run: npm run build
      - name: Release version
        run: npx unorepo-alpha version --commit --tag --push --publish --release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
